### ISSUE TITLE
Issue running Yo app on M13

### ISSUE THREAD

**Issue by mat-rizzo-r3** [roger3cev/yo-cordapp#5]
When running the Yo app, this exception happens. Then the service restarts repeatedly.

```
Aug 18 15:21:16 m13upy5rb-node2 systemd[1]: Started corda node.
Aug 18 15:21:21 m13upy5rb-node2 java[8255]:    ______               __
Aug 18 15:21:21 m13upy5rb-node2 java[8255]:   / ____/     _________/ /___ _
Aug 18 15:21:21 m13upy5rb-node2 java[8255]:  / /     __  / ___/ __  / __ `/         There was an earthquake in California,
Aug 18 15:21:21 m13upy5rb-node2 java[8255]: / /___  /_/ / /  / /_/ / /_/ /          a local bank went into de-fault.
Aug 18 15:21:21 m13upy5rb-node2 java[8255]: \____/     /_/   \__,_/\__,_/
Aug 18 15:21:21 m13upy5rb-node2 java[8255]: --- Corda Open Source 0.13.0 (17401e9) -----------------------------------------------
Aug 18 15:21:21 m13upy5rb-node2 java[8255]: New! Training now available worldwide, see https://corda.net/corda-training/
Aug 18 15:21:21 m13upy5rb-node2 java[8255]: Logs can be found in                    : /opt/corda/logs
Aug 18 15:21:25 m13upy5rb-node2 java[8255]: Database connection url is              : jdbc:h2:tcp://10.0.0.32:11000/node
Aug 18 15:21:28 m13upy5rb-node2 java[8255]: Incoming connection address             : 10.0.0.32:10002
Aug 18 15:21:29 m13upy5rb-node2 java[8255]: Exception in thread "main" java.lang.NoClassDefFoundError: net/corda/webserver/services/WebServerPluginRegistry
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.lang.ClassLoader.defineClass1(Native Method)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.security.AccessController.doPrivileged(Native Method)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.lang.Class.forName0(Native Method)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.lang.Class.forName(Class.java:348)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1038)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1071)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1062)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.core.serialization.DefaultKryoCustomizer$pluginRegistries$2.invoke(DefaultKryoCustomizer.kt:43)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.core.serialization.DefaultKryoCustomizer$pluginRegistries$2.invoke(DefaultKryoCustomizer.kt:38)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.core.serialization.DefaultKryoCustomizer.getPluginRegistries(DefaultKryoCustomizer.kt)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.core.serialization.DefaultKryoCustomizer.customize(DefaultKryoCustomizer.kt:117)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.core.serialization.KryoKt$kryoPool$1.create(Kryo.kt:463)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.borrow(KryoPoolQueueImpl.java:51)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:59)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.core.serialization.KryoKt.serialize(Kryo.kt:151)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.core.serialization.KryoKt.serialize$default(Kryo.kt:150)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.core.crypto.EncodingUtils.toBase58String(EncodingUtils.kt:67)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.nodeapi.ArtemisMessagingComponent$NodeAddress$Companion.asPeer(ArtemisMessagingComponent.kt:79)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.services.messaging.NodeMessagingClient.<init>(NodeMessagingClient.kt:137)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.Node.makeMessagingService(Node.kt:151)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.AbstractNode.makeServices(AbstractNode.kt:460)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.AbstractNode.access$makeServices(AbstractNode.kt:99)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.AbstractNode$start$3.invoke(AbstractNode.kt:224)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.AbstractNode$start$3.invoke(AbstractNode.kt:99)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.AbstractNode$initialiseDatabasePersistence$3.invoke(AbstractNode.kt:597)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.AbstractNode$initialiseDatabasePersistence$3.invoke(AbstractNode.kt:99)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:69)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:57)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.utilities.DatabaseSupportKt.transaction(DatabaseSupport.kt:48)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.AbstractNode.initialiseDatabasePersistence(AbstractNode.kt:596)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.Node.initialiseDatabasePersistence(Node.kt:304)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:223)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.Node.start(Node.kt:310)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:103)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.internal.NodeStartup.run(NodeStartup.kt:81)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at net.corda.node.Corda.main(Corda.kt:11)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]: Caused by: java.lang.ClassNotFoundException: net.corda.webserver.services.WebServerPluginRegistry
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Aug 18 15:21:29 m13upy5rb-node2 java[8255]:         ... 50 more
Aug 18 15:21:29 m13upy5rb-node2 systemd[1]: corda.service: Main process exited, code=exited, status=1/FAILURE
Aug 18 15:21:29 m13upy5rb-node2 systemd[1]: corda.service: Unit entered failed state.
Aug 18 15:21:29 m13upy5rb-node2 systemd[1]: corda.service: Failed with result 'exit-code'.
Aug 18 15:21:30 m13upy5rb-node2 systemd[1]: corda.service: Service hold-off time over, scheduling restart.
Aug 18 15:21:30 m13upy5rb-node2 systemd[1]: Stopped corda node.
```

**Comment by roger-that-dev** [comment]
Seems to work OK on my local machine... Do you have the node's config file and version to hand? Cheers mate

**Comment by roger-that-dev** [comment]
Ah.. just read the exception properly.. looks like there is a missing dependency?
